site_name: Cloudbreak 
site_favicon: /images/favicon.png
site_url: http://hortonworks.github.io/cloudbreak-documentation/
repo_url: https://github.com/hortonworks/cloudbreak-documentation
theme_dir: mkdocs_theme
theme_dir: custom_cinder
extra_css:
  - css/extra.css
dev_addr: 0.0.0.0:8000
strict: true
copyright: © 2011-2018 <a href="http://www.hortonworks.com" target="_blank">Hortonworks Inc</a>. All Rights Reserved. | <a href="http://hortonworks.com/privacy-policy/" target="_blank">Privacy Policy</a>
google_analytics: ['UA-22950817-24', 'auto']
markdown_extensions:
  - markdown_include.include
use_directory_urls: false
pages:
    - RN:
      - Index: index.md 
      - Release Notes: cb_releasenotes.md
    - Concepts: 
      - Introduction: cb_intro.md  
      - Security overview: cb_security.md
    - Planning: 
      - Deployment options: cb_deployment-options.md
    - Installation: 
      - AWS: 
        - Quickstart on AWS: cb_aws-quick.md
        - Launch on AWS: cb_aws-launch.md
        - Create a Cloudbreak credential on AWS: cb_aws-cred.md
        - Create a cluster: cb_aws-create.md 
      - Azure: 
        - Quickstart on Azure: cb_azure-quick.md
        - Launch on Azure: cb_azure-launch.md
        - Create a Cloudbreak credential on Azure: cb_azure-cred.md
        - Create a cluster: cb_azure-create.md 
      - GCP:
        - Quickstart on GCP: cb_gcp-quick.md
        - Launch on GCP: cb_gcp-launch.md
        - Create a Cloudbreak credential on GCP: cb_gcp-cred.md
        - Create a cluster: cb_gcp-create.md
      - OpenStack:
        - Launch on OpenStack: cb_os-launch.md
        - Create a Cloudbreak credential on OpenStack: cb_os-cred.md
        - Create a cluster: cb_os-create.md
      - Upgrade Cloudbreak: cb_cb-upgrade.md
      - Install the CLI: cb_cli-install.md
    - How to:
      - Configure advanced cluster options: cb_cluster-adv.md
      - Configure cloud data access: cb_data.md
      - Configure advanced Cloudbreak options: cb_cb-adv-config.md
      - Access and Manage clusters: cb_clusters-manage.md
      - Troubleshoot: cb_trouble.md
    - Reference:
      - CLI Reference: cb_cli-reference.md
      - Developer documentation links: cb_dev.md